
INSERT INTO cfp_forms (event_id, title, description, fields_json, status, version, published_at, published_json)
VALUES (
  '00000000-0000-4000-8000-000000000001',
  'Share your conference story',
  'Submit a practical session for Greenroom Demo Summit.',
  '[{"id":"title","type":"short_text","label":"Proposal title","guidance":"Keep it specific","required":true,"options":[]},{"id":"abstract","type":"long_text","label":"Abstract","guidance":"What will attendees learn?","required":true,"options":[]},{"id":"name","type":"short_text","label":"Your name","guidance":"How organizers should address you","required":false,"options":[]},{"id":"email","type":"email","label":"Contact email","guidance":"We will send your confirmation here","required":true,"options":[]},{"id":"track","type":"select","label":"Track","guidance":"Choose the programme track","required":false,"options":[],"choices":[{"id":"track-platform","label":"Platform & Infra","active":true},{"id":"track-practice","label":"Practice","active":true}]},{"id":"format","type":"select","label":"Format","guidance":"Choose the session format","required":false,"options":[],"choices":[{"id":"talk-30","label":"Talk (30 min)","active":true},{"id":"workshop-60","label":"Workshop (60 min)","active":true}]}]',
  'open',
  1,
  '2026-08-09T12:00:00.000Z',
  '{"eventId":"00000000-0000-4000-8000-000000000001","title":"Share your conference story","description":"Submit a practical session for Greenroom Demo Summit.","fields":[{"id":"title","type":"short_text","label":"Proposal title","guidance":"Keep it specific","required":true,"options":[]},{"id":"abstract","type":"long_text","label":"Abstract","guidance":"What will attendees learn?","required":true,"options":[]},{"id":"name","type":"short_text","label":"Your name","guidance":"How organizers should address you","required":false,"options":[]},{"id":"email","type":"email","label":"Contact email","guidance":"We will send your confirmation here","required":true,"options":[]},{"id":"track","type":"select","label":"Track","guidance":"Choose the programme track","required":false,"options":[],"choices":[{"id":"track-platform","label":"Platform & Infra","active":true},{"id":"track-practice","label":"Practice","active":true}]},{"id":"format","type":"select","label":"Format","guidance":"Choose the session format","required":false,"options":[],"choices":[{"id":"talk-30","label":"Talk (30 min)","active":true},{"id":"workshop-60","label":"Workshop (60 min)","active":true}]}],"status":"open","version":1,"publishedAt":"2026-08-09T12:00:00.000Z","publishedStatus":"open"}'
);
