import { isProjectionChannel } from "../../domain/communications/delivery";
import type { DomainEventConsumer, DeliveryProvider, ProviderResult } from "./ports";
import type { CommunicationsRepository } from "./ports";

const retryDelayMs = (attempt: number) => Math.min(60_000, 1_000 * 2 ** Math.max(0, attempt - 1));

/**
 * What one provider call did, for the operational log.
 *
 * Deliberately made of generated identifiers and normalized codes only. A delivery's recipient,
 * its rendered message and its payload are all absent: this line goes to a shared sink, and an
 * outbox that leaks a speaker's address into it every minute is a worse problem than the one the
 * telemetry solves.
 *
 * The idempotency key is absent for the same reason, and that one is easy to miss:
 * `POST /api/communications/deliveries` lets a caller choose it, so a delivery keyed
 * `invite:ada@example.test` would put an address here. `deliveryId` is generated by this domain
 * and is enough to find the row, which holds the rest under the same authorization as the
 * organizer's history view.
 */
export interface DeliveryAttemptRecord {
  readonly deliveryId: string;
  readonly channel: string;
  readonly triggerType: string;
  readonly sequence: number;
  readonly outcome: string;
  readonly errorCode: string | null;
  readonly providerReference: string | null;
}

export interface OutboxTelemetry {
  attempt(record: DeliveryAttemptRecord): void;
}

// @spec PRD-COM-001 PRD-INT-001 ARC-OBS-001
export class OutboxWorker {
  constructor(
    private readonly repository: CommunicationsRepository,
    private readonly providers: Record<"email" | "airtable" | "accelevents", DeliveryProvider>,
    private readonly dependencies: { newId(): string; now(): Date },
    private readonly telemetry?: OutboxTelemetry,
    /**
     * Handles `event`-channel deliveries, which carry a domain event rather than a message and
     * so have no provider to call.
     *
     * Optional because a composition that only sends mail has no events to consume, and an
     * absent consumer must not silently drop one: an `event` delivery that arrives with nothing
     * bound is failed terminally with `NO_EVENT_CONSUMER` rather than left queued forever or
     * marked succeeded. A record nobody consumed should be visible in the history as exactly
     * that.
     */
    private readonly eventConsumer?: DomainEventConsumer,
  ) {}

  async runOne(): Promise<boolean> {
    const leaseToken = this.dependencies.newId();
    const delivery = await this.repository.leaseNext(
      this.dependencies.now().toISOString(),
      leaseToken,
    );
    if (!delivery) return false;

    // The durable lease is committed before this provider call; no DB transaction is open here.
    const startedAt = this.dependencies.now().toISOString();
    const sequence = delivery.attemptCount + 1;
    if (await this.repository.isProjectionSuperseded(delivery)) {
      await this.repository.complete(
        leaseToken,
        {
          id: this.dependencies.newId(),
          deliveryId: delivery.id,
          sequence,
          startedAt,
          completedAt: startedAt,
          outcome: "terminal_failure",
          providerReference: null,
          errorCode: "PROJECTION_SUPERSEDED",
        },
        { state: "terminal", nextAttemptAt: startedAt, updatedAt: startedAt },
      );
      return true;
    }
    let result: ProviderResult;
    try {
      // An `event` delivery has no provider: it announces something that already happened here,
      // and "delivering" it means letting this system's own consumer act on it. It shares this
      // path rather than getting one of its own so a fan-out that fails halfway is retried,
      // bounded and audited by the same attempt history as a failed send.
      result =
        delivery.channel === "event"
          ? ((await this.eventConsumer?.consume(delivery)) ?? {
              kind: "terminal",
              code: "NO_EVENT_CONSUMER",
            })
          : await this.providers[delivery.channel].deliver(delivery);
    } catch {
      // ERROR-INTENT: Provider details are untrusted; normalize the failure into an auditable retry.
      result = { kind: "retryable" as const, code: "UNEXPECTED_PROVIDER_ERROR" };
    }
    const completedAt = this.dependencies.now().toISOString();
    const retryExhausted = result.kind === "retryable" && sequence >= 3;
    const state =
      result.kind === "success"
        ? "succeeded"
        : result.kind === "terminal" || retryExhausted
          ? "terminal"
          : "retrying";
    const nextAttemptAt =
      result.kind === "retryable"
        ? new Date(this.dependencies.now().getTime() + retryDelayMs(sequence)).toISOString()
        : completedAt;
    const attempt = {
      id: this.dependencies.newId(),
      deliveryId: delivery.id,
      sequence,
      startedAt,
      completedAt,
      outcome:
        result.kind === "success"
          ? ("succeeded" as const)
          : result.kind === "retryable" && !retryExhausted
            ? ("retryable_failure" as const)
            : ("terminal_failure" as const),
      providerReference: result.kind === "success" ? result.providerReference : null,
      errorCode:
        result.kind === "success"
          ? null
          : retryExhausted
            ? `RETRY_EXHAUSTED:${result.code}`
            : result.code,
    };
    await this.repository.complete(
      leaseToken,
      attempt,
      { state, nextAttemptAt, updatedAt: completedAt },
      result.kind === "success" &&
        isProjectionChannel(delivery.channel) &&
        delivery.projectionVersion !== null
        ? {
            destination: delivery.channel,
            eventId: delivery.eventId,
            resourceRef: delivery.recipientRef,
            version: delivery.projectionVersion,
            deliveryId: delivery.id,
            projectedAt: completedAt,
          }
        : undefined,
    );
    // Emitted after the attempt is durable, so the log never claims an outcome the database
    // does not hold, and guarded because a telemetry sink is not worth the queue: a throwing
    // logger would abort this drain and leave every remaining eligible delivery waiting for the
    // next tick.
    try {
      this.telemetry?.attempt({
        deliveryId: delivery.id,
        channel: delivery.channel,
        triggerType: delivery.triggerType,
        sequence,
        outcome: attempt.outcome,
        errorCode: attempt.errorCode,
        providerReference: attempt.providerReference,
      });
    } catch {
      // ERROR-INTENT: the attempt is already durable and readable in the delivery history; a
      // failed log line must not stall the outbox for every other queued delivery. The delivery
      // was processed either way, which is what the return value means.
      return true;
    }
    return true;
  }
}
